SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[TEsting_table]'
GO
ALTER TABLE [dbo].[TEsting_table] ADD
[Testing2] [int] NULL
GO
